function App() {
  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          Prototype Ready
        </h1>
        <p className="text-lg text-gray-600">
          This project was generated by AI. Check PLAN.md for requirements.
        </p>
      </div>
    </div>
  )
}

export default App
